# Generated by Django 4.2.7 on 2025-11-08 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='站点唯一标识', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='站点代码（NA/ASIA）', max_length=20, unique=True)),
                ('name', models.CharField(help_text='站点名称', max_length=100)),
                ('domain', models.CharField(help_text='站点域名', max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='站点激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'sites',
                'indexes': [models.Index(fields=['code'], name='sites_code_168f30_idx'), models.Index(fields=['is_active', 'created_at'], name='sites_is_acti_8218b9_idx')],
            },
        ),
    ]

