# Generated by Django 4.2.7 on 2025-11-09 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainAssetConfig",
            fields=[
                (
                    "config_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("ETH", "Ethereum"),
                            ("POLYGON", "Polygon"),
                            ("BSC", "BSC"),
                            ("TRON", "TRON"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_symbol", models.CharField(max_length=10)),
                ("token_decimals", models.IntegerField()),
                ("fireblocks_asset_id", models.CharField(max_length=50)),
                ("fireblocks_vault_id", models.CharField(default="0", max_length=10)),
                (
                    "address_type",
                    models.CharField(
                        choices=[("EVM", "EVM (0x...)"), ("TRON", "TRON (Base58)")],
                        default="EVM",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "db_table": "chain_asset_configs",
                "indexes": [
                    models.Index(
                        fields=["site", "is_active"],
                        name="chain_asset_site_id_dd455f_idx",
                    )
                ],
                "unique_together": {("site", "chain", "token_symbol")},
            },
        ),
    ]
