# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_enable_rls_policies"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="chk_notifications_broadcast_recipient",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_site_id_fc2ad6_idx",
            old_name="notificatio_site_id_7a3c91_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_site_id_4289d0_idx",
            old_name="notificatio_site_id_b7d24e_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_source__085bf8_idx",
            old_name="notificatio_source__6aa74a_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_severit_5abb00_idx",
            old_name="notificatio_severit_f1c45b_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_30e8f7_idx",
            old_name="notificatio_recipie_e9c723_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationchanneltask",
            new_name="notificatio_notific_a5a19b_idx",
            old_name="notificatio_notific_5f7218_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationchanneltask",
            new_name="notificatio_status_b31808_idx",
            old_name="notificatio_status_c8de4f_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationchanneltask",
            new_name="notificatio_channel_047f68_idx",
            old_name="notificatio_channel_3cd94e_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationpreference",
            new_name="notificatio_site_id_9c5b76_idx",
            old_name="notificatio_site_id_3a9e74_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationpreference",
            new_name="notificatio_user_id_b49b4a_idx",
            old_name="notificatio_user_id_7dcb19_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationreadreceipt",
            new_name="notificatio_notific_63c36c_idx",
            old_name="notificatio_notific_c1f872_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationreadreceipt",
            new_name="notificatio_user_id_bffe53_idx",
            old_name="notificatio_user_id_1e9ab3_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_site_id_68bc93_idx",
            old_name="notificatio_site_id_64cad4_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_categor_a7d616_idx",
            old_name="notificatio_categor_ac58fe_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_name_9313bc_idx",
            old_name="notificatio_name_e9d3f2_idx",
        ),
        migrations.AlterField(
            model_name="notificationreadreceipt",
            name="notification",
            field=models.ForeignKey(
                help_text="关联通知（recipient_type='site_broadcast'）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="notifications.notification",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("recipient_id__isnull", True),
                        ("recipient_type", "site_broadcast"),
                    ),
                    models.Q(
                        ("recipient_id__isnull", False),
                        ("recipient_type", "site_broadcast"),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="chk_notifications_broadcast_recipient",
            ),
        ),
    ]
