# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("errors", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="errorcode",
            new_name="error_codes_domain_01afdb_idx",
            old_name="error_codes_domain_c43bce_idx",
        ),
        migrations.RenameIndex(
            model_name="errorcode",
            new_name="error_codes_severit_751b73_idx",
            old_name="error_codes_severit_6abe1b_idx",
        ),
        migrations.RenameIndex(
            model_name="errorcode",
            new_name="error_codes_code_ae2841_idx",
            old_name="error_codes_code_f8ed2d_idx",
        ),
        migrations.RenameIndex(
            model_name="errormessage",
            new_name="error_messa_msg_key_78fab2_idx",
            old_name="error_messa_msg_key_e0b5a2_idx",
        ),
    ]
