# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0002_commission_plans"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="commissionplan",
            new_name="commission__site_id_10ef36_idx",
            old_name="commission_plans_site_id_7f8d42_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionplan",
            new_name="commission__site_id_c101f3_idx",
            old_name="commission_plans_site_id_8e7c31_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionplantier",
            new_name="commission__plan_id_27a735_idx",
            old_name="commission_plan_tiers_plan_id_9f6d52_idx",
        ),
    ]
