# Generated by Django 4.2.7 on 2025-11-08 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStats',
            fields=[
                ('stat_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='统计记录ID', primary_key=True, serialize=False)),
                ('site_id', models.UUIDField(db_index=True, help_text='站点ID（RLS隔离）')),
                ('agent', models.UUIDField(db_index=True, help_text='代理用户ID', unique=True)),
                ('total_customers', models.PositiveIntegerField(default=0, help_text='累计客户数')),
                ('direct_customers', models.PositiveIntegerField(default=0, help_text='直接客户数（depth=1）')),
                ('total_sales', models.DecimalField(decimal_places=6, default=0, help_text='累计销售额（USD）', max_digits=18)),
                ('total_commissions', models.DecimalField(decimal_places=6, default=0, help_text='累计佣金', max_digits=18)),
                ('last_order_at', models.DateTimeField(blank=True, help_text='最后订单时间', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Stats',
                'verbose_name_plural': 'Agent Stats',
                'db_table': 'agent_stats',
            },
        ),
        migrations.CreateModel(
            name='AgentTree',
            fields=[
                ('tree_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='关系唯一标识', primary_key=True, serialize=False)),
                ('site_id', models.UUIDField(db_index=True, help_text='站点ID（RLS隔离）')),
                ('agent', models.UUIDField(db_index=True, help_text='代理用户ID（关联 users.user_id）')),
                ('parent', models.UUIDField(blank=True, db_index=True, help_text='上级代理ID（NULL=根节点）', null=True)),
                ('depth', models.PositiveSmallIntegerField(default=1, help_text='深度（1=直接推荐）')),
                ('path', models.TextField(help_text='路径（/root/parent/agent/）')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Tree',
                'verbose_name_plural': 'Agent Trees',
                'db_table': 'agent_trees',
                'indexes': [models.Index(fields=['site_id', 'agent'], name='agent_trees_site_id_6cbd95_idx'), models.Index(fields=['site_id', 'parent'], name='agent_trees_site_id_6ccb37_idx'), models.Index(fields=['site_id', 'active'], name='agent_trees_site_id_6c271c_idx'), models.Index(fields=['depth'], name='agent_trees_depth_5f7073_idx'), models.Index(fields=['created_at'], name='agent_trees_created_5fa2ff_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agenttree',
            constraint=models.UniqueConstraint(fields=('site_id', 'agent', 'parent'), name='unique_site_agent_parent'),
        ),
        migrations.AddIndex(
            model_name='agentstats',
            index=models.Index(fields=['site_id', 'agent'], name='agent_stats_site_id_a98e69_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstats',
            index=models.Index(fields=['total_sales'], name='agent_stats_total_s_ac6dec_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstats',
            index=models.Index(fields=['last_order_at'], name='agent_stats_last_or_71bc8b_idx'),
        ),
    ]

