# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_statement_balance_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentprofile",
            new_name="agent_profi_site_id_0d2ac3_idx",
            old_name="agent_profiles_site_id_8d7f42_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprofile",
            new_name="agent_profi_site_id_6786c9_idx",
            old_name="agent_profiles_site_id_9e6c31_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprofile",
            new_name="agent_profi_site_id_62cf67_idx",
            old_name="agent_profiles_site_id_7f5b20_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprofile",
            new_name="agent_profi_kyc_sta_88d103_idx",
            old_name="agent_profiles_kyc_sta_6d4e19_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionstatement",
            new_name="commission__agent_p_f71d01_idx",
            old_name="commission_statements_agent_p_9d8f43_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionstatement",
            new_name="commission__period__bd6647_idx",
            old_name="commission_statements_period__7e6d32_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionstatement",
            new_name="commission__generat_b39298_idx",
            old_name="commission_statements_generat_8f5c21_idx",
        ),
        migrations.RenameIndex(
            model_name="withdrawalrequest",
            new_name="withdrawal__agent_p_6ca6c2_idx",
            old_name="withdrawal_requests_agent_p_8c9f32_idx",
        ),
        migrations.RenameIndex(
            model_name="withdrawalrequest",
            new_name="withdrawal__status_c15858_idx",
            old_name="withdrawal_requests_status_7b8e21_idx",
        ),
        migrations.RenameIndex(
            model_name="withdrawalrequest",
            new_name="withdrawal__approve_ce75bc_idx",
            old_name="withdrawal_requests_approve_6d7c10_idx",
        ),
    ]
