# Generated by POSX Framework

from django.db import migrations


class Migration(migrations.Migration):
    """
    ⭐ Phase C 核心检查点 #1: RLS 索引创建
    
    CRITICAL:
    - atomic = False（支持 CONCURRENTLY）
    - site_id + created_at 复合索引
    - fireblocks_tx_id 唯一索引（allocations）
    
    参考: PRODUCTION_CHECKLIST.md § 核心检查点 #1
    """

    atomic = False  # ⭐ 必须：支持 CONCURRENTLY

    dependencies = [
        # ('core', '0002_create_initial_schema'),  # ⚠️ 已删除,DB已就绪
    ]

    operations = [
        # Orders 表索引
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_site_created ON orders(site_id, created_at);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_orders_site_created;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_status ON orders(status);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_orders_status;"
        ),

        # Tiers 表索引
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tiers_site_active ON tiers(site_id, is_active);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_tiers_site_active;"
        ),

        # Commissions 表索引
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_commissions_site_status ON commissions(site_id, status);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_commissions_site_status;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_commissions_agent ON commissions(agent_id);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_commissions_agent;"
        ),

        # Allocations 表索引
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_allocations_site_status ON allocations(site_id, status);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_allocations_site_status;"
        ),
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_allocations_fireblocks_tx ON allocations(fireblocks_tx_id) WHERE fireblocks_tx_id IS NOT NULL;",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_allocations_fireblocks_tx;"
        ),

        # Users 表索引
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_wallet ON users(wallet_address);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_users_wallet;"
        ),

        # Sites 表索引
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_sites_code ON sites(code);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_sites_code;"
        ),
    ]

