# Generated by POSX Framework

from django.db import migrations
import os


class Migration(migrations.Migration):
    """
    ⭐ Phase C 核心检查点 #4: 启用 RLS 策略
    
    CRITICAL:
    - 强制行级安全（FORCE ROW LEVEL SECURITY）
    - UUID 类型转换（::uuid）
    - admin 只读权限
    - 完整 reverse_sql
    
    参考: PRODUCTION_CHECKLIST.md § 核心检查点 #1
    """

    dependencies = [
        ('core', '0003_create_rls_indexes'),
    ]

    # ⭐ Railway Demo 环境临时跳过（需要 posx_admin 角色）
    # 部署时设置环境变量 SKIP_RLS_POLICIES=1 即可跳过
    operations = [] if os.getenv('SKIP_RLS_POLICIES') == '1' else [
        migrations.RunSQL(
            sql="""
                -- ============================================
                -- 启用 RLS：orders
                -- ============================================
                ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
                ALTER TABLE orders FORCE ROW LEVEL SECURITY;

                -- 创建策略：用户只能访问自己站点的数据
                CREATE POLICY rls_orders_site_isolation ON orders
                    FOR ALL
                    USING (site_id = current_setting('app.current_site_id', true)::uuid)
                    WITH CHECK (site_id = current_setting('app.current_site_id', true)::uuid);

                -- Admin 只读权限（所有站点）
                CREATE POLICY rls_orders_admin_readonly ON orders
                    FOR SELECT
                    TO posx_admin
                    USING (true);

                -- ============================================
                -- 启用 RLS：tiers
                -- ============================================
                ALTER TABLE tiers ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tiers FORCE ROW LEVEL SECURITY;

                CREATE POLICY rls_tiers_site_isolation ON tiers
                    FOR ALL
                    USING (site_id = current_setting('app.current_site_id', true)::uuid)
                    WITH CHECK (site_id = current_setting('app.current_site_id', true)::uuid);

                CREATE POLICY rls_tiers_admin_readonly ON tiers
                    FOR SELECT
                    TO posx_admin
                    USING (true);

                -- ============================================
                -- 启用 RLS：commissions
                -- ============================================
                ALTER TABLE commissions ENABLE ROW LEVEL SECURITY;
                ALTER TABLE commissions FORCE ROW LEVEL SECURITY;

                CREATE POLICY rls_commissions_site_isolation ON commissions
                    FOR ALL
                    USING (site_id = current_setting('app.current_site_id', true)::uuid)
                    WITH CHECK (site_id = current_setting('app.current_site_id', true)::uuid);

                CREATE POLICY rls_commissions_admin_readonly ON commissions
                    FOR SELECT
                    TO posx_admin
                    USING (true);

                -- ============================================
                -- 启用 RLS：allocations
                -- ============================================
                ALTER TABLE allocations ENABLE ROW LEVEL SECURITY;
                ALTER TABLE allocations FORCE ROW LEVEL SECURITY;

                CREATE POLICY rls_allocations_site_isolation ON allocations
                    FOR ALL
                    USING (site_id = current_setting('app.current_site_id', true)::uuid)
                    WITH CHECK (site_id = current_setting('app.current_site_id', true)::uuid);

                CREATE POLICY rls_allocations_admin_readonly ON allocations
                    FOR SELECT
                    TO posx_admin
                    USING (true);

                -- ============================================
                -- 防止 site_id 被修改（触发器）
                -- ============================================
                CREATE OR REPLACE FUNCTION forbid_site_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF OLD.site_id != NEW.site_id THEN
                        RAISE EXCEPTION 'site_id cannot be changed after creation';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                -- 应用到核心表
                CREATE TRIGGER prevent_site_change_orders
                    BEFORE UPDATE ON orders
                    FOR EACH ROW
                    EXECUTE FUNCTION forbid_site_change();

                CREATE TRIGGER prevent_site_change_tiers
                    BEFORE UPDATE ON tiers
                    FOR EACH ROW
                    EXECUTE FUNCTION forbid_site_change();

                CREATE TRIGGER prevent_site_change_commissions
                    BEFORE UPDATE ON commissions
                    FOR EACH ROW
                    EXECUTE FUNCTION forbid_site_change();

                CREATE TRIGGER prevent_site_change_allocations
                    BEFORE UPDATE ON allocations
                    FOR EACH ROW
                    EXECUTE FUNCTION forbid_site_change();
            """,
            reverse_sql="""
                -- ============================================
                -- 回滚：禁用 RLS 和清理触发器
                -- ============================================
                
                -- 删除触发器
                DROP TRIGGER IF EXISTS prevent_site_change_allocations ON allocations;
                DROP TRIGGER IF EXISTS prevent_site_change_commissions ON commissions;
                DROP TRIGGER IF EXISTS prevent_site_change_tiers ON tiers;
                DROP TRIGGER IF EXISTS prevent_site_change_orders ON orders;
                DROP FUNCTION IF EXISTS forbid_site_change();
                
                -- 删除 allocations 策略并禁用 RLS
                DROP POLICY IF EXISTS rls_allocations_admin_readonly ON allocations;
                DROP POLICY IF EXISTS rls_allocations_site_isolation ON allocations;
                ALTER TABLE allocations DISABLE ROW LEVEL SECURITY;
                
                -- 删除 commissions 策略并禁用 RLS
                DROP POLICY IF EXISTS rls_commissions_admin_readonly ON commissions;
                DROP POLICY IF EXISTS rls_commissions_site_isolation ON commissions;
                ALTER TABLE commissions DISABLE ROW LEVEL SECURITY;
                
                -- 删除 tiers 策略并禁用 RLS
                DROP POLICY IF EXISTS rls_tiers_admin_readonly ON tiers;
                DROP POLICY IF EXISTS rls_tiers_site_isolation ON tiers;
                ALTER TABLE tiers DISABLE ROW LEVEL SECURITY;
                
                -- 删除 orders 策略并禁用 RLS
                DROP POLICY IF EXISTS rls_orders_admin_readonly ON orders;
                DROP POLICY IF EXISTS rls_orders_site_isolation ON orders;
                ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]

