# Generated by Django 4.2.7 on 2025-11-09 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_add_idempotency_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_site_idempotency_key",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="ord_status_exp_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="ord_site_idem_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancelled_reason",
        ),
    ]
