# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_enable_promo_codes_rls"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promo_codes_site_id_2c97b0_idx",
            old_name="promo_codes_site_active_idx",
        ),
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promo_codes_code_5b1d05_idx",
            old_name="promo_codes_code_idx",
        ),
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promo_codes_valid_f_9f992f_idx",
            old_name="promo_codes_valid_period_idx",
        ),
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promo_codes_created_afc7d8_idx",
            old_name="promo_codes_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promo_code__promo_c_469618_idx",
            old_name="promo_usage_promo_code_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promo_code__order_i_631ef7_idx",
            old_name="promo_usage_order_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promo_code__user_id_ed96ab_idx",
            old_name="promo_usage_user_promo_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promo_code__created_993b41_idx",
            old_name="promo_usage_created_at_idx",
        ),
        migrations.AlterField(
            model_name="promocode",
            name="promo_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="促销码唯一标识",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="promocodeusage",
            name="usage_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="使用记录唯一标识",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
