# Generated by Django 4.2.7 on 2025-11-08 18:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='分配唯一标识', primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='收币钱包地址（快照，lowercase）', max_length=42)),
                ('token_amount', models.DecimalField(decimal_places=6, help_text='代币数量', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='分配状态', max_length=20)),
                ('fireblocks_tx_id', models.CharField(blank=True, db_index=True, help_text='Fireblocks交易ID（幂等键）', max_length=255, null=True, unique=True)),
                ('tx_hash', models.CharField(blank=True, help_text='链上交易哈希', max_length=255, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='确认时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='关联订单（一对一）', on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='orders.order')),
            ],
            options={
                'verbose_name': 'Allocation',
                'verbose_name_plural': 'Allocations',
                'db_table': 'allocations',
                'indexes': [models.Index(fields=['order'], name='allocations_order_i_8cfed5_idx'), models.Index(fields=['status', 'created_at'], name='allocations_status_fe35d6_idx'), models.Index(fields=['fireblocks_tx_id'], name='allocations_fireblo_81cc86_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='chk_allocation_status'),
        ),
    ]

