# Generated by Django 4.2.7 on 2025-11-09 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allocations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="allocation",
            name="chk_allocation_status",
        ),
        migrations.RemoveIndex(
            model_name="allocation",
            name="allocations_fireblo_81cc86_idx",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="fireblocks_tx_id",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="tx_hash",
        ),
        migrations.AddField(
            model_name="allocation",
            name="released_tokens",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="已发放到链上的代币数量（累加）",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("completed", "Completed")],
                db_index=True,
                default="active",
                help_text="分配状态",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["active", "completed"])),
                name="chk_allocation_status",
            ),
        ),
    ]
