# Generated by Django 4.2.7 on 2025-11-08 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='记录唯一标识', primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='幂等键（webhook事件ID）', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('fireblocks', 'Fireblocks')], db_index=True, help_text='来源系统', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='处理时间')),
                ('payload', models.JSONField(blank=True, help_text='原始payload（用于排查）', null=True)),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['key', 'source'], name='idempotency_key_f43c7b_idx'), models.Index(fields=['source', 'processed_at'], name='idempotency_source_5807bf_idx'), models.Index(fields=['processed_at'], name='idempotency_process_90c0da_idx')],
            },
        ),
    ]

