# Generated by Django 4.2.7 on 2025-11-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="idempotencykey",
            name="idempotency_key_f43c7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="idempotencykey",
            name="idempotency_source_5807bf_idx",
        ),
        migrations.AlterField(
            model_name="idempotencykey",
            name="key",
            field=models.CharField(help_text="幂等键（webhook事件ID）", max_length=200),
        ),
        # ⭐ 修复：UUID → BigAutoField 需要先删除再创建
        migrations.RunSQL(
            sql="ALTER TABLE idempotency_keys DROP COLUMN key_id CASCADE;",
            reverse_sql="-- No reverse"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE idempotency_keys ADD COLUMN key_id bigserial PRIMARY KEY;",
            reverse_sql="-- No reverse"
        ),
        migrations.AlterUniqueTogether(
            name="idempotencykey",
            unique_together={("source", "key")},
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["source", "key"], name="idempotency_source_9a2bab_idx"
            ),
        ),
    ]
