# Generated by Django 4.2.7 on 2025-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0003_webhook_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_source_75d941_idx",
            old_name="webhook_events_source_8f7d42_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_tx_id_8cbb52_idx",
            old_name="webhook_events_tx_id_6c3e91_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_created_8fa52f_idx",
            old_name="webhook_events_created_5b2d80_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_source_683499_idx",
            old_name="webhook_events_source_9d8f43_idx",
        ),
        migrations.AlterField(
            model_name="idempotencykey",
            name="key_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
