# Generated by Django 4.2.7 on 2025-11-08 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommissionPolicySnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='快照唯一标识', primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True, help_text='关联订单ID（OneToOne）', unique=True)),
                ('plan_id', models.UUIDField(help_text='佣金计划ID（快照时）')),
                ('plan_name', models.CharField(help_text='计划名称', max_length=100)),
                ('plan_version', models.PositiveIntegerField(help_text='计划版本')),
                ('plan_mode', models.CharField(help_text='计算模式', max_length=20)),
                ('diff_reward_enabled', models.BooleanField(default=False, help_text='是否启用差额奖励')),
                ('tiers_json', models.JSONField(help_text='层级配置（JSONB 格式）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Commission Policy Snapshot',
                'verbose_name_plural': 'Order Commission Policy Snapshots',
                'db_table': 'order_commission_policy_snapshots',
                'indexes': [models.Index(fields=['order_id'], name='order_commi_order_i_ea2a3a_idx'), models.Index(fields=['plan_id'], name='order_commi_plan_id_f73749_idx'), models.Index(fields=['created_at'], name='order_commi_created_990fb8_idx')],
            },
        ),
    ]

