# Generated by Django 4.2.7 on 2025-11-09 02:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0004_remove_order_unique_site_idempotency_key_and_more"),
        ("allocations", "0002_remove_allocation_chk_allocation_status_and_more"),
        ("sites", "0002_chainassetconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="VestingPolicy",
            fields=[
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "tge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="TGE立即释放百分比 (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("cliff_months", models.IntegerField(default=0, help_text="锁定期（月）")),
                ("linear_periods", models.IntegerField(help_text="分期数量")),
                (
                    "period_unit",
                    models.CharField(
                        choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "db_table": "vesting_policies",
            },
        ),
        migrations.CreateModel(
            name="VestingSchedule",
            fields=[
                (
                    "schedule_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("total_tokens", models.DecimalField(decimal_places=6, max_digits=18)),
                ("tge_tokens", models.DecimalField(decimal_places=6, max_digits=18)),
                ("locked_tokens", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unlock_start_date", models.DateField(help_text="线性释放开始日期")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocations.allocation",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vesting_schedule",
                        to="orders.order",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vesting.vestingpolicy",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "vesting_schedules",
            },
        ),
        migrations.CreateModel(
            name="VestingRelease",
            fields=[
                (
                    "release_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("period_no", models.IntegerField(help_text="期数（0=TGE）")),
                ("release_date", models.DateField(help_text="计划释放日期")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("processing", "Processing"),
                            ("released", "Released"),
                        ],
                        db_index=True,
                        default="locked",
                        max_length=20,
                    ),
                ),
                (
                    "chain_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="链上实际转账数量",
                        max_digits=24,
                        null=True,
                    ),
                ),
                (
                    "fireblocks_tx_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Fireblocks交易ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, help_text="链上交易哈希", max_length=100, null=True
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(blank=True, help_text="解锁时间", null=True),
                ),
                (
                    "released_at",
                    models.DateTimeField(blank=True, help_text="发放完成时间", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="vesting.vestingschedule",
                    ),
                ),
            ],
            options={
                "db_table": "vesting_releases",
            },
        ),
        migrations.AddIndex(
            model_name="vestingschedule",
            index=models.Index(
                fields=["site", "user"], name="vesting_sch_site_id_98f760_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vestingschedule",
            index=models.Index(
                fields=["unlock_start_date"], name="vesting_sch_unlock__3a54b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vestingrelease",
            index=models.Index(
                fields=["status", "unlocked_at"], name="vesting_rel_status_5d5327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vestingrelease",
            index=models.Index(
                fields=["fireblocks_tx_id"], name="vesting_rel_fireblo_9b5e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vestingrelease",
            index=models.Index(
                fields=["release_date"], name="vesting_rel_release_b09dd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vestingrelease",
            unique_together={("schedule", "period_no")},
        ),
        migrations.AlterUniqueTogether(
            name="vestingpolicy",
            unique_together={("site", "name")},
        ),
    ]
