# Generated by Django 4.2.7 on 2025-11-08 18:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='计划唯一标识', primary_key=True, serialize=False)),
                ('site_id', models.UUIDField(db_index=True, help_text='站点ID（RLS隔离）')),
                ('name', models.CharField(help_text='计划名称', max_length=100)),
                ('version', models.PositiveIntegerField(default=1, help_text='版本号')),
                ('mode', models.CharField(choices=[('level', 'Level-based'), ('solar_diff', 'Solar Differential')], default='level', help_text='计算模式', max_length=20)),
                ('diff_reward_enabled', models.BooleanField(default=False, help_text='是否启用差额奖励')),
                ('effective_from', models.DateTimeField(blank=True, help_text='生效开始时间', null=True)),
                ('effective_to', models.DateTimeField(blank=True, help_text='生效结束时间', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='激活状态（同站点同名仅一个active）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Plan',
                'verbose_name_plural': 'Commission Plans',
                'db_table': 'commission_plans',
            },
        ),
        migrations.CreateModel(
            name='CommissionPlanTier',
            fields=[
                ('tier_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='层级配置唯一标识', primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(help_text='层级（1-10）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rate_percent', models.DecimalField(decimal_places=2, help_text='费率百分比（0-100）', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('min_sales', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='该层级最低销售额', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('diff_cap_percent', models.DecimalField(blank=True, decimal_places=2, help_text='差额封顶百分比（仅solar_diff模式）', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('hold_days', models.PositiveSmallIntegerField(default=7, help_text='佣金冻结天数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='所属计划', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commission_plans.commissionplan')),
            ],
            options={
                'verbose_name': 'Commission Plan Tier',
                'verbose_name_plural': 'Commission Plan Tiers',
                'db_table': 'commission_plan_tiers',
                'ordering': ['level'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['site_id', 'name', 'version'], name='commission__site_id_dfdb49_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['site_id', 'is_active'], name='commission__site_id_c101f3_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['effective_from', 'effective_to'], name='commission__effecti_cdda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplan',
            index=models.Index(fields=['created_at'], name='commission__created_f927df_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.UniqueConstraint(fields=('site_id', 'name', 'version'), name='unique_site_plan_version'),
        ),
        migrations.AddIndex(
            model_name='commissionplantier',
            index=models.Index(fields=['plan', 'level'], name='commission__plan_id_27a735_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionplantier',
            constraint=models.UniqueConstraint(fields=('plan', 'level'), name='unique_plan_level'),
        ),
    ]

